server.port=${PORT:8080}
spring.application.name=bfhl-api

bfhl.user.full-name=Anushka Yadav
bfhl.user.email=anushkayadav230422@acropolis.in
bfhl.user.roll-number=0827IT231027
bfhl.user.dob=18/02/2006
